service: platform-teams

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  environment:
    TEAMS_TABLE: ${file(./config/${self:provider.stage}.json):TEAMS_TABLE}
    INVITES_TABLE: ${file(./config/${self:provider.stage}.json):INVITES_TABLE}
    MEMBERSHIPS_TABLE: ${file(./config/${self:provider.stage}.json):MEMBERSHIPS_TABLE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*"


functions:
  create_team:
    handler: handler.create_team
    events:
      - http: 
          path: create_team
          method: post
  invite_to_team:
    handler: handler.invite_to_team
    events:
      - http: 
          path: invite_to_team
          method: post
  join_team:
    handler: handler.join_team
    events:
      - http: 
          path: join_team
          method: post
  leave_team:
    handler: handler.leave_team
    events:
      - http: 
          path: leave_team
          method: post

plugins:
  - serverless-jest-plugin
custom:
  # see https://github.com/nordcloud/serverless-jest-plugin
  jest:
    collectCoverage: true
