'use strict';

// tests for posting a sponsor, then getting it
// Generated by serverless-jest-plugin

const mod = require('./../handler');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;

const post_sponsor_url = "https://8cefcll545.execute-api.us-east-1.amazonaws.com/dev/add_sponsor"
const get_sponsors_url = "https://8cefcll545.execute-api.us-east-1.amazonaws.com/dev/get_sponsorship_info"
const Axios = require('axios');


async function getData(url) {
  try {
    const result = await Axios.get(`${url}`);
    return result.data;
  } catch (e) {
    console.error(e);
  }
}

let example_sponsor = {
  "tier": "Gold",
  "name": "Apple",
  "events_hosted": ["Intro to Swift"],
  "logo_image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1000px-Apple_logo_black.svg.png"
};

describe('add_sponsor', () => {

  it('uploads a sponsor, then retrieves it', async () => {

    Axios.post(post_sponsor_url, example_sponsor)
    .then(async function (response) {
      // console.log(response);
      // test getting the posted data
      let resp = await getData(get_sponsors_url);
      // console.log(resp);
      expect(resp).toBeDefined();

      let filtered = resp.filter(sponsor => sponsor['name'] == example_sponsor["name"]);
      expect(filtered.length > 0).toBe(true);

      // TODO: delete the data in the DB
    })
    .catch(function (error) {
      console.log(error);
      return false
    });

  });
});
