// tests for add_sponsor
// Generated by serverless-jest-plugin

const jestPlugin = require('serverless-jest-plugin');
const mod = require('../handler');

const { lambdaWrapper } = jestPlugin;
const adder = lambdaWrapper.wrap(mod, { handler: 'add_sponsor' });
const getter = lambdaWrapper.wrap(mod, { handler: 'get_sponsorship_info' });

const example_sponsor = {
  tier: 'Gold',
  name: 'Apple',
  events_hosted: ['Intro to Swift'],
  logo_image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Apple_logo_black.svg/1000px-Apple_logo_black.svg.png',
};

describe('add_sponsor', () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('uploads a sponsor, then retrieves it', async () => {
    const event = {
      body: JSON.stringify(example_sponsor),
    };

    const resp = adder.run(event).then((response) => {
      expect(response).toBeDefined();
      expect(response).toMatchObject({ body: {}, statusCode: 200 });
      // console.log(response);
    });

    return getter.run({}).then((response) => {
      expect(response).toBeDefined();
      // console.log(response);
      const filtered = JSON.parse(response.body).filter((sponsor) => sponsor.name == example_sponsor.name);
      expect(filtered.length > 0).toBe(true);
    });

    // TODO: remove uploaded data from db
  });
});
