// tests for get_sponsorship_info
// Generated by serverless-jest-plugin

const jestPlugin = require('serverless-jest-plugin');
const mod = require('../handler');

const { lambdaWrapper } = jestPlugin;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'get_sponsorship_info' });

describe('get_sponsorship_info', () => {
  beforeAll((done) => {
    done();
  });

  it('Correctly returns table', async () => {
    const request = {
      TableName: process.env.SPONSORS_INFO_TABLE,
    };
    return await wrapped.run(request).then(async (response) => {
      expect(response).toBeDefined();
      expect(response).toHaveProperty('statusCode', 200);
    });
  });
});
