'use strict';

// tests for create_team
// Generated by serverless-jest-plugin

const mod = require('./../handler');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'create_team' });

const AWS = require('aws-sdk-mock');

const sample_team = {
    team_name: "A cool team"
}


describe('create_team', () => {
  beforeAll((done) => {
    done();
  });

  it('Correctly inserts the team into the database', () => {
    const bodyStub = sample_team;
    AWS.mock('DynamoDB', 'putItem', function(params, callback) {
      callback(null, {Item: sample_team});
    });

    const team = {
      body: JSON.stringify(bodyStub)
    };
    return wrapped.run(team).then((response) => {
      expect(response).toBeDefined();
      expect(response).toMatchObject({body: JSON.stringify(sample_team), statusCode: 200})
    });
  });

});
