'use strict';

// tests for create_team
// Generated by serverless-jest-plugin

const mod = require('./../handler');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'create_team' });

const AWS = require('aws-sdk-mock');

const sample_invite = {
    "team_id": "12jj32k42-sdfjk32",
    "user_id": "2j3kjfd9sfjdsk-23"
}


describe('invite_to_team', () => {
  beforeAll((done) => {
    done();
  });

  it('Correctly inserts the invite into the database', () => {
    const bodyStub = sample_invite;
    AWS.mock('DynamoDB', 'putItem', function(params, callback) {
      callback(null, {Item: sample_invite});
    });

    const invite = {
      body: JSON.stringify(bodyStub)
    };
    return wrapped.run(invite).then((response) => {
      expect(response).toBeDefined();
      expect(response).toMatchObject({body: JSON.stringify(sample_invite), statusCode: 200})
    });
  });

});
