service: platform-users

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  environment:
    USERS_TABLE: ${file(./config/${self:provider.stage}.json):USERS_TABLE}
    INVITES_TABLE: ${file(./config/${self:provider.stage}.json):INVITES_TABLE}
    INVITE_TEMPLATE_ID: ${file(./config/${self:provider.stage}.json):INVITE_TEMPLATE_ID}
    BASE_INVITE_URL: ${file(./config/${self:provider.stage}.json):BASE_INVITE_URL}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*"

functions:
  delete_user:
    handler: handler.delete_user
    events:
      - http: 
          path: delete_user
          method: post
          cors: true
  get_user:
    handler: handler.get_user
    events:
      - http: 
          path: get_user
          method: get
          cors: true
  add_user:
    handler: handler.add_user
    events:
      - http: 
          path: add_user
          method: post
          cors: true
  update_user:
    handler: handler.update_user
    events:
      - http: 
          path: update_user
          method: post
          cors: true
  invite_user:
    handler: handler.invite_user
    events:
      - http: 
          path: invite_user
          method: post
          cors: true
plugins:
  - serverless-jest-plugin
custom:
  # see https://github.com/nordcloud/serverless-jest-plugin
  jest:
    collectCoverage: true