export default {
  dev: {
    SCHEDULE_BASE_ENDPOINT: 'https://dxz39cp5d0.execute-api.us-east-1.amazonaws.com',
    SAMPLE_USER_ID: 'SAMPLE_USER_ID',
    SIGNUP_FORM_LINK: 'https://gotechnica.org',
    USERS_BASE_ENDPOINT: 'https://xgyrlul4tk.execute-api.us-east-1.amazonaws.com',
    SPONSORS_INFO_ENDPOINT: 'https://8cefcll545.execute-api.us-east-1.amazonaws.com',
    LIVESTREAM_LINK: 'https://www.youtube.com/channel/UC-Wo4UqhGUKQEp4o-51VMIw',
    SPONSORSHIP_LINK: 'https://www.vfairs.com/',
    TEAMS_BASE_ENDPOINT: 'https://e2hezie6kb.execute-api.us-east-1.amazonaws.com',
    PROJECTS_BASE_ENDPOINT: 'https://4yngdno31k.execute-api.us-east-1.amazonaws.com',
    PRIZES_LINK: 'https://technica2019.devpost.com/#prizes',
    HACKER_RESOURCES_LINK: 'https://docs.google.com/document/d/1jUgCjvzZqAYbus2QMwfcaubS67R9mcfzfOPzEKpf4OY/edit?usp=sharing',
  },
  testing: {
    SCHEDULE_BASE_ENDPOINT: 'https://dxz39cp5d0.execute-api.us-east-1.amazonaws.com',
    SAMPLE_USER_ID: 'SAMPLE_USER_ID',
    SIGNUP_FORM_LINK: 'https://gotechnica.org',
    USERS_BASE_ENDPOINT: 'https://xgyrlul4tk.execute-api.us-east-1.amazonaws.com',
    SPONSORS_INFO_ENDPOINT: 'https://8cefcll545.execute-api.us-east-1.amazonaws.com',
    LIVESTREAM_LINK: 'https://www.youtube.com/channel/UC-Wo4UqhGUKQEp4o-51VMIw',
    SPONSORSHIP_LINK: 'https://www.vfairs.com/',
    TEAMS_BASE_ENDPOINT: 'https://e2hezie6kb.execute-api.us-east-1.amazonaws.com',
    PROJECTS_BASE_ENDPOINT: 'https://8cefcll545.execute-api.us-east-1.amazonaws.com',
    PRIZES_LINK: 'https://technica2019.devpost.com/#prizes',
    HACKER_RESOURCES_LINK: 'https://docs.google.com/document/d/1jUgCjvzZqAYbus2QMwfcaubS67R9mcfzfOPzEKpf4OY/edit?usp=sharing',
  },
  stage: {
    SPONSORS_INFO_ENDPOINT: 'https://jxeehdxaq6.execute-api.us-east-1.amazonaws.com',
    SCHEDULE_BASE_ENDPOINT: 'https://n1zcgon3ub.execute-api.us-east-1.amazonaws.com',
    SAMPLE_USER_ID: 'SAMPLE_USER_ID',
    SIGNUP_FORM_LINK: 'https://gotechnica.org',
    USERS_BASE_ENDPOINT: 'https://xhy30yrm0f.execute-api.us-east-1.amazonaws.com',
    LIVESTREAM_LINK: 'https://www.youtube.com/channel/UC-Wo4UqhGUKQEp4o-51VMIw',
    SPONSORSHIP_LINK: 'https://www.vfairs.com/',
    PROJECTS_BASE_ENDPOINT: 'https://jxeehdxaq6.execute-api.us-east-1.amazonaws.com',
    TEAMS_BASE_ENDPOINT: 'https://c6vffjuklb.execute-api.us-east-1.amazonaws.com',
    PRIZES_LINK: 'https://technica2019.devpost.com/#prizes',
    HACKER_RESOURCES_LINK: 'https://docs.google.com/document/d/1jUgCjvzZqAYbus2QMwfcaubS67R9mcfzfOPzEKpf4OY/edit?usp=sharing',
  },
  prod: {
    SPONSORS_INFO_ENDPOINT: 'https://phqk5kktqi.execute-api.us-east-1.amazonaws.com',
    SCHEDULE_BASE_ENDPOINT: 'https://n1zcgon3ub.execute-api.us-east-1.amazonaws.com',
    SAMPLE_USER_ID: 'SAMPLE_USER_ID',
    SIGNUP_FORM_LINK: 'https://gotechnica.org',
    USERS_BASE_ENDPOINT: 'https://nc0gm7vx1i.execute-api.us-east-1.amazonaws.com',
    LIVESTREAM_LINK: 'https://www.youtube.com/channel/UC-Wo4UqhGUKQEp4o-51VMIw',
    SPONSORSHIP_LINK: 'https://www.vfairs.com/',
    PROJECTS_BASE_ENDPOINT: 'https://phqk5kktqi.execute-api.us-east-1.amazonaws.com',
    TEAMS_BASE_ENDPOINT: ' https://v0usve1q3f.execute-api.us-east-1.amazonaws.com',
    PRIZES_LINK: 'https://technica2019.devpost.com/#prizes',
    HACKER_RESOURCES_LINK: 'https://docs.google.com/document/d/1jUgCjvzZqAYbus2QMwfcaubS67R9mcfzfOPzEKpf4OY/edit?usp=sharing',
  },
};
