export default {
  shared: {
    SAMPLE_ZOOM_LINK: 'https://us04web.zoom.us/j/9191971697?pwd=U1lPSUlJeElXQldCTkJwSnJOYjB4dz09',
    LIVESTREAM_LINK: 'https://www.youtube.com/embed/5jPwFWIvBzk',
    SLACK_INVITE_LINK: 'https://join.slack.com/t/technica2020/shared_invite/zt-higqqg9d-njO1xc8o__xAKhLyId_kvw',
    DOCUSIGN_WAIVER_LINK: 'https://docusign.com',
    VIDEO_MONTAGE_LINK: 'https://getmontage.co/s/0JQ0',
    START_DATE: '2020-10-25',
    END_DATE: '2020-10-26',
  },
  dev: {
    SCHEDULE_BASE_ENDPOINT: 'https://dxz39cp5d0.execute-api.us-east-1.amazonaws.com',
    SAMPLE_USER_ID: 'SAMPLE_USER_ID',
    SIGNUP_FORM_LINK: 'https://gotechnica.org',
    USERS_BASE_ENDPOINT: 'https://9zxvldglh9.execute-api.us-east-1.amazonaws.com',
    SPONSORS_INFO_ENDPOINT: 'https://4yngdno31k.execute-api.us-east-1.amazonaws.com',
    SPONSORSHIP_LINK: 'https://www.vfairs.com/',
    TEAMS_BASE_ENDPOINT: 'https://bqjydw3dzk.execute-api.us-east-1.amazonaws.com',
    PROJECTS_BASE_ENDPOINT: 'https://4yngdno31k.execute-api.us-east-1.amazonaws.com',
    PRIZES_LINK: 'https://technica2019.devpost.com/#prizes',
    HACKER_RESOURCES_LINK: 'https://docs.google.com/document/d/1jUgCjvzZqAYbus2QMwfcaubS67R9mcfzfOPzEKpf4OY/edit?usp=sharing',
    SLACK_WORKSPACE_LINK: 'https://slack.com',
    PLATFORM_WALKTHROUGH_ID: '146643',
    ADMIN_BASE_ENDPOINT: 'https://pdrb4smpwd.execute-api.us-east-1.amazonaws.com',
  },
  testing: {
    SCHEDULE_BASE_ENDPOINT: 'https://dxz39cp5d0.execute-api.us-east-1.amazonaws.com',
    SAMPLE_USER_ID: 'SAMPLE_USER_ID',
    SIGNUP_FORM_LINK: 'https://gotechnica.org',
    USERS_BASE_ENDPOINT: 'https://xgyrlul4tk.execute-api.us-east-1.amazonaws.com',
    SPONSORS_INFO_ENDPOINT: 'https://8cefcll545.execute-api.us-east-1.amazonaws.com',
    SPONSORSHIP_LINK: 'https://www.vfairs.com/',
    TEAMS_BASE_ENDPOINT: 'https://e2hezie6kb.execute-api.us-east-1.amazonaws.com',
    PROJECTS_BASE_ENDPOINT: 'https://8cefcll545.execute-api.us-east-1.amazonaws.com',
    PRIZES_LINK: 'https://technica2019.devpost.com/#prizes',
    HACKER_RESOURCES_LINK: 'https://docs.google.com/document/d/1jUgCjvzZqAYbus2QMwfcaubS67R9mcfzfOPzEKpf4OY/edit?usp=sharing',
    SLACK_WORKSPACE_LINK: 'https://slack.com',
    PLATFORM_WALKTHROUGH_ID: '146643',
    ADMIN_BASE_ENDPOINT: 'https://pdrb4smpwd.execute-api.us-east-1.amazonaws.com',
  },
  stage: {
    SPONSORS_INFO_ENDPOINT: 'https://jxeehdxaq6.execute-api.us-east-1.amazonaws.com',
    SCHEDULE_BASE_ENDPOINT: 'https://n1zcgon3ub.execute-api.us-east-1.amazonaws.com',
    SAMPLE_USER_ID: 'SAMPLE_USER_ID',
    SIGNUP_FORM_LINK: 'https://gotechnica.org',
    USERS_BASE_ENDPOINT: 'https://xhy30yrm0f.execute-api.us-east-1.amazonaws.com',
    SPONSORSHIP_LINK: 'https://www.vfairs.com/',
    PROJECTS_BASE_ENDPOINT: 'https://jxeehdxaq6.execute-api.us-east-1.amazonaws.com',
    TEAMS_BASE_ENDPOINT: 'https://c6vffjuklb.execute-api.us-east-1.amazonaws.com',
    PRIZES_LINK: 'https://technica2019.devpost.com/#prizes',
    HACKER_RESOURCES_LINK: 'https://docs.google.com/document/d/1jUgCjvzZqAYbus2QMwfcaubS67R9mcfzfOPzEKpf4OY/edit?usp=sharing',
    SLACK_WORKSPACE_LINK: 'https://slack.com',
    PLATFORM_WALKTHROUGH_ID: '146643',
    ADMIN_BASE_ENDPOINT: 'https://riskeip135.execute-api.us-east-1.amazonaws.com',
  },
  prod: {
    SPONSORS_INFO_ENDPOINT: 'https://phqk5kktqi.execute-api.us-east-1.amazonaws.com',
    SCHEDULE_BASE_ENDPOINT: 'https://urbd4h6d6d.execute-api.us-east-1.amazonaws.com',
    SAMPLE_USER_ID: 'SAMPLE_USER_ID',
    SIGNUP_FORM_LINK: 'https://gotechnica.org',
    USERS_BASE_ENDPOINT: 'https://nc0gm7vx1i.execute-api.us-east-1.amazonaws.com',
    SPONSORSHIP_LINK: 'https://www.vfairs.com/',
    PROJECTS_BASE_ENDPOINT: 'https://phqk5kktqi.execute-api.us-east-1.amazonaws.com',
    TEAMS_BASE_ENDPOINT: ' https://v0usve1q3f.execute-api.us-east-1.amazonaws.com',
    PRIZES_LINK: 'https://technica2019.devpost.com/#prizes',
    HACKER_RESOURCES_LINK: 'https://docs.google.com/document/d/1jUgCjvzZqAYbus2QMwfcaubS67R9mcfzfOPzEKpf4OY/edit?usp=sharing',
    SLACK_WORKSPACE_LINK: 'https://slack.com',
    PLATFORM_WALKTHROUGH_ID: '146643',
    ADMIN_BASE_ENDPOINT: 'https://68186188hl.execute-api.us-east-1.amazonaws.com',
  },
};
