'use strict';

// tests for add_event_to_user_list
// Generated by serverless-jest-plugin

const mod = require('./../handler');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'add_event_to_user_list' });

const AWS = require('aws-sdk-mock');

const valid_case = {
  event_id: "5",
  user_id: "j32kg32v3-323j2"
}

const invalid_case = {
  user_id: "j32kg32v3-323j2"
}

describe('add_event_to_user_list', () => {
  beforeAll((done) => {
    done();
  });

  it('Correctly inserts the selection into the database', () => {
    const bodyStub = valid_case;
    AWS.mock('DynamoDB', 'putItem', function(params, callback) {
      callback(null, {Item: valid_case});
    });

    const event = {
      body: JSON.stringify(bodyStub)
    };
    return wrapped.run(event).then((response) => {
      expect(response).toBeDefined();
      expect(response).toHaveProperty('statusCode', 200);
      expect(JSON.parse(response.body)).toHaveProperty('id');
    });
  });

  it('Correctly fails if an invalid input is given', () => {
    const bodyStub = invalid_case;
    AWS.mock('DynamoDB', 'putItem', function(params, callback) {
      callback(null, {Item: invalid_case});
    });

    const event = {
      body: JSON.stringify(bodyStub)
    };
    return wrapped.run(event).then((response) => {
      expect(response).toBeDefined();
      expect(response).toHaveProperty('statusCode', 500);
    });
  });
});
