'use strict';

// tests for get_schedule
// Generated by serverless-jest-plugin

const mod = require('./../handler');

const AWS = require('aws-sdk');
const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'get_schedule' });

const sample_schedule = [
  {
      id: {S: "1"},
      category: {S: "main"},
      description: {S: "A very cool workshop for Technica!"},
      start_time: {S: "2020-6-5T15:00:00Z"},
      end_time: {S: "2020-6-5T18:00:00Z"},
  },
  {
      id: {S: "2"},
      category: {S: "main"},
      description: {S: "Another very cool workshop for Technica!"},
      start_time: {S: "2020-6-5T15:00:00Z"},
    end_time: {S: "2020-6-5T18:00:00Z"},
  }
];


describe('get_schedule', () => {
  beforeAll((done) => {
    done();
  });

  it('Correctly retrieves the schedule from the database', () => {

    return wrapped.run().then((response) => {
      expect(response).toBeDefined();
      expect(response).toHaveProperty('statusCode', 200);
    });
  });
});
