org: technica
app: platform-admin
service: platform-admin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: platform-admin-${self:provider.stage}-layers-deploymentbucket
  environment:
    SENTRY_DSN: ${file(./config/${self:provider.stage}.json):SENTRY_DSN}
    ADMIN_TABLE: ${file(./config/${self:provider.stage}.json):ADMIN_TABLE}
    EASTER_EGGS_TABLE:  ${file(./config/${self:provider.stage}.json):EASTER_EGGS_TABLE}
    SPONSOR_BOOTHS_TABLE:  ${file(./config/${self:provider.stage}.json):SPONSOR_BOOTHS_TABLE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*"


functions:
  get_easter_eggs:
    handler: handler.get_easter_eggs
    description: Retrieves all easter egg data for a particular user
    events:
      - http:
          path: get_easter_eggs
          method: get
          cors: true
  add_easter_eggs_for_user:
    handler: handler.add_easter_eggs_for_user
    description: Adds easter eggs to DB for user
    events:
      - http:
          path: add_easter_eggs_for_user
          method: post
          cors: true
  discover_easter_egg:
    handler: handler.discover_easter_egg
    description: Updates the discover value for a particular easter egg
    events:
      - http:
          path: discover_easter_egg
          method: post
          cors: true
  add_sponsor_booth:
    handler: handler.add_sponsor_booth
    description: Adds a sponsor booth to the DB
    events:
      - http:
          path: add_sponsor_booth
          method: post
          cors: true
  update_sponsor_booth:
    handler: handler.update_sponsor_booth
    description: Updates a sponsor booth in the DB
    events:
      - http:
          path: update_sponsor_booth
          method: post
          cors: true
  get_sponsor_booths:
    handler: handler.get_sponsor_booths
    description: Retrieves all sponsor booths
    events:
      - http:
          path: get_sponsor_booths
          method: get
          cors: true
  get_sponsor_booth:
    handler: handler.get_sponsor_booth
    description: Retrieves a specific sponsor booth
    events:
      - http:
          path: get_sponsor_booth
          method: get
          cors: true
plugins:
  - serverless-sentry
  - serverless-jest-plugin
  - serverless-layers

custom:
  sentry:
    dsn: ${file(./config/${self:provider.stage}.json):SENTRY_DSN}
  # see https://github.com/nordcloud/serverless-jest-plugin
  jest:
    collectCoverage: true
  serverless-layers:
    dependenciesPath: ./package.json