service: platform-schedule

provider:
  name: aws
  region: us-east-1
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  environment:
    SCHEDULE_TABLE: ${file(./config/${self:provider.stage}.json):SCHEDULE_TABLE}
    USER_EVENTS_TABLE: ${file(./config/${self:provider.stage}.json):USER_EVENTS_TABLE}
    SHORTLINKS_TABLE: ${file(./config/${self:provider.stage}.json):SHORTLINKS_TABLE}
    SHORTLINK_CLICKS_TABLE: ${file(./config/${self:provider.stage}.json):SHORTLINK_CLICKS_TABLE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*"

functions:
  get_schedule:
    handler: handler.get_schedule
    description: Retrieves all schedule data from database
    events:
      - http: 
          path: schedule
          method: get
          cors: true
  get_event:
    handler: handler.get_event
    description: Retrieves single schedule event from database
    events:
      - http: 
          path: get_event
          method: get
          cors: true
  add_event:
    handler: handler.add_event
    description: Adds a new schedule event to the database
    events:
      - http: 
          path: add_event
          method: post
          cors: true
  update_event:
    handler: handler.update_event
    description: Updates an existing schedule event to the database
    events:
      - http: 
          path: update_event
          method: post
          cors: true
  add_event_to_user_list:
    handler: handler.add_event_to_user_list
    description: Adds a new schedule event to the a user's list
    events:
      - http: 
          path: add_event_to_user_list
          method: post
          cors: true
  delete_event_from_user_list:
    handler: handler.delete_event_from_user_list
    description: Deletes a schedule event from a user's list
    events:
      - http:
          path: delete_event_from_user_list
          method: post
          cors: true
  add_shortlink:
    handler: handler.add_shortlink
    description: Adds a unique shortlink to the database
    events:
      - http:
          path: add_shortlink
          method: post
          cors: true
  get_shortlink:
    handler: handler.get_shortlink
    description: Gets a shortlink from the database
    events:
      - http:
          path: get_shortlink
          method: get
          cors: true        
  add_shortlink_click:
    handler: handler.add_shortlink_click
    description: Adds a shortlink click event to the database
    events:
      - http:
          path: add_shortlink_click
          method: post
          cors: true

          

plugins:
  - serverless-jest-plugin
custom:
  # see https://github.com/nordcloud/serverless-jest-plugin
  jest:
    collectCoverage: true
