service: platform-projects

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  environment:
    PROJECTS_TABLE: ${file(./config/${self:provider.stage}.json):PROJECTS_TABLE}
    SPONSORS_INFO_TABLE: ${file(./config/${self:provider.stage}.json):SPONSORS_INFO_TABLE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*"


functions:
  add_sponsor:
    handler: handler.add_sponsor
    description: Adds a new sponsor to the database
    events:
      - http: 
          path: add_sponsor
          method: post
          cors: true
  get_sponsorship_info:
    handler: handler.get_sponsorship_info
    description: gets sponsorship info from the database
    events:
      - http: 
          path: get_sponsorship_info
          method: get
          cors: true

plugins:
  - serverless-jest-plugin
custom:
  # see https://github.com/nordcloud/serverless-jest-plugin
  jest:
    collectCoverage: true