org: technica
app: platform-projects
service: platform-projects

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  environment:
    SENTRY_DSN: ${file(./config/${self:provider.stage}.json):SENTRY_DSN}
    PROJECTS_TABLE: ${file(./config/${self:provider.stage}.json):PROJECTS_TABLE}
    SPONSORS_INFO_TABLE: ${file(./config/${self:provider.stage}.json):SPONSORS_INFO_TABLE}
    MENTORSHIP_REQUESTS_TABLE: ${file(./config/${self:provider.stage}.json):MENTORSHIP_REQUESTS_TABLE}
    DEVPOST_LINK_TABLE: ${file(./config/${self:provider.stage}.json):DEVPOST_LINK_TABLE}
    PROJECT_SUBMISSION_CHECKLIST_ITEMS_TABLE: ${file(./config/${self:provider.stage}.json):PROJECT_SUBMISSION_CHECKLIST_ITEMS_TABLE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*"


functions:
  add_sponsor:
    handler: handler.add_sponsor
    description: Adds a new sponsor to the database
    events:
      - http: 
          path: add_sponsor
          method: post
          cors: true
  get_sponsorship_info:
    handler: handler.get_sponsorship_info
    description: gets sponsorship info from the database
    events:
      - http: 
          path: get_sponsorship_info
          method: get
          cors: true
  get_active_mentorship_requests:
    handler: handler.get_active_mentorship_requests
    description: gets active mentorship requests from the database
    events:
      - http: 
          path: get_active_mentorship_requests
          method: get
          cors: true
  update_mentorship_request:
    handler: handler.update_mentorship_request
    description: update a mentorship request
    events:
      - http: 
          path: update_mentorship_request
          method: post
          cors: true
  get_user_mentorship_requests:
    handler: handler.get_user_mentorship_requests
    description: gets mentorship requests created by a specified user
    events:
      - http: 
          path: get_user_mentorship_requests
          method: get
          cors: true
  create_mentorship_request:
    handler: handler.create_mentorship_request
    description: adds a new mentorship request to the database
    events:
      - http: 
          path: create_mentorship_request
          method: post
          cors: true
  create_project_submission:
    handler: handler.create_project_submission
    description: creates a project submission to devpost
    events:
      - http:
          path: create_project_submission
          method: post
          cors: true
  create_project_checklist_item:
    handler: handler.create_project_checklist_item
    description: adds a new project submission checklist item to the database
    events:
      - http: 
          path: create_project_checklist_item
          method: post
          cors: true
  get_project_checklist_item:
    handler: handler.get_project_checklist_item
    description: gets a project submission checklist item from the database
    events:
      - http: 
          path: get_project_checklist_item
          method: get
          cors: true
  update_project_checklist_item:
    handler: handler.update_project_checklist_item
    description: updates an existing project submission checklist item in the database
    events:
      - http: 
          path: update_project_checklist_item
          method: post
          cors: true

plugins:
  - serverless-sentry
  - serverless-jest-plugin

custom:
  sentry:
    dsn: ${file(./config/${self:provider.stage}.json):SENTRY_DSN}
  # see https://github.com/nordcloud/serverless-jest-plugin
  jest:
    collectCoverage: true