name: Deploy admin backend service

# Controls when the action will run. Triggered from a "repository dispatch",
# a.k.a. an HTTP request to a certain endpoint
on:
  repository_dispatch:
    types: deploy-all-backend
  push:
    branches:
      - master

# Job simply sends a dispatch to the repository, triggering all the other
# deploy-backend-{service}.yml jobs
jobs:
  deploy:
    name: Deploy all backend services
    runs-on: ubuntu-latest

    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: deploy-backend
        # Notify slack that a run has been triggered
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: Initiated new backend platform deploy to staging. View this deployment at https://github.com/gotechnica/platform-2020/actions
        MSG_MINIMAL: true
        SLACK_TITLE: Event
