# This is a basic workflow to help you get started with Actions

name: Deploy backend admin service on push to master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths:
      - backend/admin


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: switch to admin dir
      run: |
        cd backend/admin
        npm ci
   
    - name: serverless deploy admin service
      uses: serverless/github-action@master
      with:
        args: deploy -s stage
        entrypoint: backend/admin
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
